version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: api
    restart: always
    env_file:
      - list.env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis